# Generated by Django 3.0 on 2019-12-16 05:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STOCK',
            fields=[
                ('stockId', models.CharField(max_length=5000, primary_key=True, serialize=False, unique=True)),
                ('LastSearched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TEXTARTIC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textArticle', models.TextField()),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('stcokId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsCentral.STOCK')),
            ],
        ),
        migrations.CreateModel(
            name='HIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('stcokId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsCentral.STOCK')),
            ],
        ),
        migrations.CreateModel(
            name='LINK',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('linkUrl', models.URLField(default='', max_length=1000, unique=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('imageLinkUrl', models.URLField(default='', max_length=1000)),
                ('title', models.TextField(default='')),
                ('stcok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LinksUrls', to='NewsCentral.STOCK')),
            ],
            options={
                'unique_together': {('stcok', 'linkUrl')},
            },
        ),
    ]
